#!/bin/bash


AUTOPOWEROFF_DOC_DIR=`pwd`

AURIGADOC_SCRIPT=`which aurigadoc.sh`
export AURIGADOC_HOME=$(cd `dirname "${AURIGADOC_SCRIPT}"`; cd ..; pwd)
cd "${AURIGADOC_HOME}"
aurigadoc.sh -html \
  -XML "${AUTOPOWEROFF_DOC_DIR}/autopoweroff.xml" \
  -OUT "${AUTOPOWEROFF_DOC_DIR}/index.html"

#firefox index.html
#aurigadoc.sh -html -XML autopoweroff.xml -OUT out/autopoweroff.html
#aurigadoc.sh -pdf  -XML autopoweroff.xml -OUT out/autopoweroff.pdf
