#!/bin/bash

if [ "${INSTALLTYPE}" != "RPM" ]; then 
  echo -e "\nProceeding with the installation.\n"; 
  [ ! -e ${gladedir}/autopoweroff.png ] && \
    ln -s ${pixmapsdir}/autopoweroff.png ${gladedir}/.
  echo "${gladedir}/autopoweroff.png" \
    >>${autopoweroff_sharedir}/autopoweroff.uninstall

  # Comment by Hans Deragon, 2006/09/27, 17:07 EDT
  #
  # consolehelper will only work if the configuration files for it are
  # enabled in /etc.  This if ${sysconfdir} is not setup to /etc,
  # consolehelper will not work and there would be no point installing
  # it.  When the user will execute it, and error message would show up
  # (it is "Unkown error."; not very useful) and useless bug reports
  # will be filed in.
  #
  # This is why we install the consolehelper symlink only if
  # ${sysconfdir} is set to /etc.
  if [ "${sysconfidr}" = "/etc" -a "${consolehelperpath}" != "not found" ]; then
    mkdir -p ${bindir}
    cd ${bindir}
    ln -s ${consolehelperpath} autopoweroff
  fi
fi

# "make" requires that this script exits with '0' if everything went well.
exit 0
